name: Show Successful Deploy

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Mock Deployment Step
        run: echo "Deployment successful!"

      # Create a new deployment
      - name: Create Deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/deployments
          ref: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_REPO_TOKEN }} 

      # Mark the deployment as successful
      - name: Mark Deployment as Successful
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/deployments/${{ fromJson(steps.create-deployment.outputs.data).id }}/statuses
          state: success
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_REPO_TOKEN }}

