name: Mock Deployment and Trigger Test

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Mock Deployment Step
        run: echo "Deployment successful!"

      - name: Create Deployment
        uses: octokit/request-action@v2.x
        id: create-deployment
        with:
          route: POST /repos/${{ github.repository }}/deployments
          ref: ${{ github.sha }}
          required_contexts: '[]'
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_REPO_TOKEN }}

      - name: Mark Deployment as Successful
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/deployments/${{ fromJson(steps.create-deployment.outputs.data).id }}/statuses
          state: success
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_REPO_TOKEN }}

      - name: Trigger Test Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEMO_REPO_TOKEN }}
          repository: myblueprint-spaces/qa-selenium
          event-type: trigger-tests
