name: Trigger test in another repository

on:
  deployment_status:

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    # Check if the deployment was successful
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEMO_REPO_TOKEN }}
          repository: myblueprint-spaces/qa-selenium
          event-type: trigger-tests
          client-payload: '{"github": ${{ toJson(github) }}}'
